version: '3.2'
services:
    app:
        build:
            context: ./vendor/rmoore/docker/services/app
        volumes:
            - .:/app

    php:
        build:
            context: ./vendor/rmoore/docker/services/php
        volumes:
            - .:/app

    nginx:
        build:
            context: ./vendor/rmoore/docker/services/nginx
        volumes:
            - .:/app
        ports:
            - 8080:80

    redis:
        image: redis

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

volumes:
    mysql_data:
