version: '3.2'
services:
    app:
        build:
            context: ./vendor/rmoore/docker/services/app
        volumes:
            - .:/app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis

    php:
        build:
            context: ./vendor/rmoore/docker/services/php
        volumes:
            - .:/app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis

    nginx:
        build:
            context: ./vendor/rmoore/docker/services/nginx
        volumes:
            - .:/app
        ports:
            - 8080:80

    redis:
        image: redis

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - 33061:3306

    webpack:
        build:
            context: ./vendor/rmoore/docker/services/webpack
        volumes:
            - .:/app
        restart: on-failure

    horizon:
        build:
            context: ./vendor/rmoore/docker/services/horizon
        volumes:
            - .:/app
        restart: unless-stopped
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            REDIS_HOST: redis
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis

    cron:
        build:
            context: ./vendor/rmoore/docker/services/cron
        volumes:
            - .:/app

volumes:
    mysql_data:
