version: '3.2'
services:
    app:
        build:
            context: ./vendor/rmoore/docker/services/app
        volumes:
            - .:/app:cached
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis

    php:
        build:
            context: ./vendor/rmoore/docker/services/php
        volumes:
            - .:/app:cached
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            REDIS_HOST: redis

    nginx:
        build:
            context: ./vendor/rmoore/docker/services/nginx
        volumes:
            - .:/app:cached
        ports:
            - 8080:80

    redis:
        image: redis

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - 33061:3306

    webpack:
        build:
            context: ./vendor/rmoore/docker/services/webpack
        volumes:
            - .:/app:cached
        restart: on-failure

    horizon:
        build:
            context: ./vendor/rmoore/docker/services/horizon
        volumes:
            - .:/app:cached
        restart: unless-stopped
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            REDIS_HOST: redis
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis

    cron:
        build:
            context: ./vendor/rmoore/docker/services/cron
        volumes:
            - .:/app:cached
            
    ngrok:
        image: gtriggiano/ngrok-tunnel
        environment:
            TARGET_HOST: nginx
            TARGET_PORT: 80
            NGROK_REGION: eu
     
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
        ports:
            - 9200:9200
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            - "discovery.type=single-node"

    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.2
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: "http://elasticsearch:9200"

volumes:
    mysql_data:
